### ISSUE TITLE
Possible speedup of _prominent_peaks method

### ISSUE THREAD

**Issue by telegraphic** [mritools/cupyimg#19]
Hi there, I have been using the `_prominent_peaks` method in [peak.py](https://github.com/mritools/cupyimg/blob/52c9abcb6b1978449ef0a8bb3c774a4bcb66ab07/cupyimg/skimage/feature/peak.py#L348), and it's running a bit slow for my application so I was looking to optimise it. I thought I would open an issue as opposed to a pull request because a) the underscore suggests this is for internal use only, and b) I'm not 100% sure my changes give identical behaviour. 

I noted that [than existing lines 395-400](https://github.com/mritools/cupyimg/blob/52c9abcb6b1978449ef0a8bb3c774a4bcb66ab07/cupyimg/skimage/feature/peak.py#L395) are the bottleneck when using on my dataset. These lines label the data then use regionprops to find coordinate centroids, which ends up calling a [cpu-based scipy find_objects function](https://github.com/mritools/cupyimg/blob/52c9abcb6b1978449ef0a8bb3c774a4bcb66ab07/cupyimg/skimage/measure/_regionprops.py#L1235).

It seems to me these lines could be changed to avoid regionprops, simply finding the peak pixels in `img_t` and then sorting the coordinate list 

```python 
    # Find array (x,y) indexes corresponding to max pixels
    peak_idxs = cp.argwhere(img_t)
    # Find corresponding maximum values
    peak_vals = img[peak_idxs[:, 0], peak_idxs[:, 1]]
    # Sort peak values low to high
    val_sort_idx = cp.argsort(peak_vals)[::-1]
    # Return (x,y) coordinates corresponding to sorted max pixels
    coords = peak_idxs[val_sort_idx]
```

This runs much faster (at least for me)! Our data is roughly (200 px, 1M px) so an unusual shape.

I also noticed in some cases, when there are a lot of peaks the `for ycoords_idx, xcoords_idx in coords:` loop is the bottleneck (or if I smoothed the data heavily beforehand). I'm still trying to get my head around what that loop is doing though 🤯.

Thanks!
Danny

**Comment by grlee77** [comment]
Yes, regionprops is one area that is not currently well-accelerated on the GPU. I think it is somewhat difficult because often each region is relatively small in terms of the number of pixels and we currently launch separate CUDA kernels per region, so this can be pretty inefficient.

The form above does give a differing result in the following test case (taken from `cupyimg/skimage/feature/tests/test_peak.py`) where the peak is actually made up of three pixels of identical intensity. The implementation here (and in upstream scikit-image) will return the centroid of these 3 voxels which is at location (7, 7) while for the proposed code here I would get (8, 8) which is part of the peak, but is not the centroid. Whether or not this matters to the user is probably application-dependent.

```Python
image = cp.zeros((15, 15))
x0, y0, i0 = (8, 8, 1)
x1, y1, i1 = (7, 7, 1)  # prominent peak
x2, y2, i2 = (6, 6, 1)
image[y0, x0] = i0
image[y1, x1] = i1
image[y2, x2] = i2
out = peak._prominent_peaks(image, min_xdistance=3, min_ydistance=3)
```

I would suggest opening an issue at upstream scikit-image to discuss with other maintainers there who work with this peak detection module more than myself. Perhaps there can be a flag for a faster mode that does not guarantee returning the centroid of the peaks. If we settle on the API on the CPU side for core scikit-image then we are more willing to make a corresponding change for the GPU.

Also, the `cupyimg.skimage` functions in this repository have recently migrated over to a new home at https://github.com/rapidsai/cucim. I still need to update the main README file here to reflect that. There are some performance improvements made in the cuCIM repository vs. here, but I don't think these include the peak finding or regionprops functions, unfortunately. The functions in `skimage.color` conversions are one thing that is much faster in the new repository and a number of functions across the library do a better job of preserving single precision computations for single precision inputs.

**Comment by telegraphic** [comment]
Thanks @grlee77 for the quick and comprehensive response! I didn't consider identical intensities, so see why labelling + regionprops was used now. 

For our needs, a small change in centroid doesn't matter. I will see what other speedups we can come up with and if it looks useful I'll get in touch with scikit-image folks. And will check out cucim. Thanks for cupyimg, it's been very helpful :).
